version: "3.8"
services:
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - db_data:/var/lib/postgresql/data
  dbviewer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on: 
      - db
  dbviewer2:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: docker@admin.com
      PGADMIN_DEFAULT_PASSWORD: docker
    depends_on: 
      - db
volumes:
  db_data:
    driver: local